name: Deploy Storybook
on: 
  pull_request: 
    branches: [main]
    types: ['opened', 'edited', 'synchronize']
    paths: 
      - 'stories/**'
      - 'src/components/**'
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v3

    - name: Install
      run: |
        yarn install --frozen-lockfile

    - uses: nelonoel/branch-name@v1.0.1

    - name: Deploy preview to Netlify
      uses: jsmrcaga/action-netlify-deploy@master
      with:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_DEPLOY_TO_PROD: false
        build_directory: storybook-static
        deploy_alias: ${{ env.BRANCH_NAME }}
        node_version: 16
        build_command: yarn build-storybook
        NETLIFY_DEPLOY_MESSAGE: |
          Preview link successfully created. please visit the following link
          https://${{ env.BRANCH_NAME }}--lawnmower-ui-storybook.netlify.app.

    - name: Status check
      uses: Sibz/github-status-action@v1.1.1
      with:
        authToken: ${{ secrets.GITHUB_TOKEN }}
        context: Netlify preview
        state: success
        target_url: https://${{ env.BRANCH_NAME }}--lawnmower-ui-storybook.netlify.app
        
